services:
  - type: web
    name: freezer-inventory
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build && npm run migrate && npm run seed
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: file:/opt/render/project/src/data/prod.db
    disk:
      name: freezer-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
